on:
  push:
    branches: master

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: git config user.name "GitHub Actions" && git config user.email "actions@users.noreply.github.com"

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master
      
      - name: install libcurl4
        run: sudo apt-get install libcurl4-openssl-dev
        
      - name: install libssh2-1-dev
        run: sudo apt-get install libssh2-1-dev

      - name: install libudunits2-dev et al 
        run: sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev
        
      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ubuntu-18.04-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ubuntu-18.04

      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_dev("pkgdown")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        run: pkgdown::deploy_to_branch(new_process = FALSE)
        shell: Rscript {0}
